---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev
  namespace: flux-system
spec:
  chart:
    spec:
      chart: test-apps
      sourceRef:
        kind: GitRepository
        name: helm-charts
  install: {}
  interval: 30s
  targetNamespace: dev
  values:
    replicaCount: 1

